### ISSUE TITLE
[Enhancement] Add an animation to the main logo

### ISSUE THREAD

**Issue by yannis300307** [CoCoSol007/website#4]
It could be well to add an animation to the logo when we load the website such as a fading and/or a translation.

**Comment by CoCoSol007** [comment]
Fix with this two commit: [1](https://github.com/CoCoSol007/website/commit/f456184) and [2](https://github.com/CoCoSol007/website/commit/3a1ad81)

**Comment by CoCoSol007** [comment]
maybe I should add a delay ?

**Comment by yannis300307** [comment]
Do ou have a preview ?

**Comment by yannis300307** [comment]
Oh it's uploaded. Yes maybe 1 or 2 seconds.

**Comment by CoCoSol007** [comment]
I've added delay and I think that more time would be too much. What do you think?

**Comment by yannis300307** [comment]
It's nice! but maybe It could be even better if the animation of the logo was after the text. Maybe 0.2s after the begginning or the text fading.

**Comment by CoCoSol007** [comment]
Ok I can try...

**Comment by CoCoSol007** [comment]
I've decided to remove the animations from my site because they didn't match the aesthetic and minimalist look I wanted to give this web page. I'm therefore closing this issue.
